
services:

  postgres:
    image: postgres:15
    container_name: filmexa-postgres
    restart: always
    env_file:
      - ./.env

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network
  
  backend:
    image: mbaanni/filmexa-backend:latest
    container_name: filmexa-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - shared-network
volumes:
  postgres_data:

networks:
  shared-network:
    external: true
    name: filmexa-net
