spring.application.name=stream

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# logging.level.org.springframework.security=TRACE

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto = create-drop

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.show-sql=true
# springdoc.swagger-ui.enabled=false

# JWT Configuration
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME}
security.jwt.refresh-expiration-time=${SECURITY_JWT_REFRESH_EXPIRATION_TIME}

# Email Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

security.verification.expiration-minutes=${SECURITY_VERIFICATION_EXPIRATION_MINUTES:15}

# Storage
app.img-storage-path=${IMG_STORAGE_PATH}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.config.import=optional:file:.env[.properties]