spring.application.name=stream

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto = create-drop

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.show-sql=true
# springdoc.swagger-ui.enabled=false

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

spring.config.import=optional:file:.env[.properties]